### PR TITLE
Adding a `--version` for the command.

### PR DESCRIPTION
**Pull request by Zoramite**
Also adding in version checking for the command.

### CODE REVIEW

**Comment by jeremydw** [comment]
I think we should avoid bloating the file tree with files if we can get away with it. I think fewer files reduce the barrier of entry to contributors.

Could we follow this rule? If a function is only going to be used in one place, avoid breaking it out into a separate file until it makes sense to have >1 function in that file? (In other words, since there's nothing else in sdk.ts now, don't create a separate sdk.ts until it's needed)

**Comment by Zoramite** [comment]
I separated it out since there were other utility information that I was going to add dealing with the sdk, like getting the current version, the latest version from a remote source, update checks, etc.

I guess for the node version check we will only use that when doing commands.

**Comment by jeremydw** [comment]
I don't think we should add update checks or that stuff to this project and instead keep it lean. Do other JS projects have that feature? Since we are going to entirely rely on npm/yarn for distribution here (and for invoking the commands) I think we can leave these bits out of the core? @stevenle do you know how other JS projects handle this, if at all?

**Review by jeremydw — APPROVED** [review]
LGTM - QQ - do we need the SemVer module? Trying to keep things as super lean as possible when it comes to dependencies so if it's not really needed... maybe we just take it out?

(For users - it's very satisfying to be able to `npm i` and have it install everything without having to recompile a bunch of stuff)

**Comment by Zoramite** [comment]
It isn't in this case, if we do an 'update check' in the future it will be handy since it will help with comparison and handles things like `alpha` and `beta` versions.

**Comment by jeremydw** [comment]
Sg -- let's add it when needed and not before. :) (Also, we can continue to rely on npm for managing versions and checking for updates, etc.)

**Pull request merged**
