### PR TITLE
Add pull request flow to Contributing guide

### PR DESCRIPTION
**Pull request by jeremydw**

### CODE REVIEW

**Review by stevenle — COMMENTED** [review]
so actually this might be debatable, but i actually like the merge commit message if we require PRs for every push to `main`. it helps track which PR contributed to the commit(s) and any discussion that went on related to the change.

so i'm of the opinion that all commits need to be rebased and squashed before committing, but keep the merge commit so we know what PR it came from. wdyt?

**Comment by jeremydw** [comment]
Oh, that's an interesting thought. I guess another way to approach it might be to just always require that the contributor include the PR # (which GitHub does by default) in the eventual "squashed and merged" commit subject? Sometimes I strip it manually which I could stop doing as you're right -- it's a useful link to the relevant discussion.

If preserved, then it could be easily referenced that way without having the extra commit (although it's obviously not clickable).

image

**Comment by stevenle** [comment]
that sounds fine to me as long as there's some reference.

**Comment by jeremydw** [comment]
Sg, updated the guidelines with a note on preserving the PR#

**Review by Zoramite — APPROVED** [review]

**Pull request merged**
